In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [5]:
for e in L:
    print(e)

1
2
3


In [6]:
for e in A:
    print(e)

1
2
3


In [7]:
L.append(4)
L

[1, 2, 3, 4]

In [8]:
L = L + [5]
L

[1, 2, 3, 4, 5]

In [9]:
A + A

array([2, 4, 6])

In [10]:
A * 2

array([2, 4, 6])

In [11]:
A * A

array([1, 4, 9])

In [12]:
A ** 2

array([1, 4, 9])

In [13]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [14]:
np.square(A)

array([1, 4, 9])

In [15]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [16]:
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])