# Vectors and Metrices

In [1]:
import numpy as np

In [5]:
M = np.array([[1,2], [3,4]])
M

array([[1, 2],
       [3, 4]])

In [6]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [7]:
L[0][0]

1

In [8]:
M[0][0]

1

In [9]:
M[0,0]

1

In [10]:
M2 = np.matrix([[1,2], [3,4]])
M2

matrix([[1, 2],
        [3, 4]])

In [11]:
M.T

array([[1, 3],
       [2, 4]])

In [12]:
Z = np.zeros(10)
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
M_Z = np.zeros((10,10))
M_Z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [14]:
M_I = np.ones((10,10))
M_I

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [15]:
M_rand = np.random.random((10,10))
M_rand

array([[ 0.57247964,  0.16630176,  0.91533308,  0.06242528,  0.46153254,
         0.66966028,  0.18746688,  0.15340916,  0.98739807,  0.49314051],
       [ 0.96522031,  0.16330746,  0.81703747,  0.54195611,  0.76394813,
         0.73370541,  0.95362454,  0.44490903,  0.88727835,  0.00491503],
       [ 0.71433288,  0.46720743,  0.38382934,  0.50579918,  0.20687928,
         0.2609291 ,  0.14456184,  0.92051726,  0.04214624,  0.29710601],
       [ 0.00233503,  0.73761068,  0.38531885,  0.9738388 ,  0.28739401,
         0.83358374,  0.6557134 ,  0.78356975,  0.08923278,  0.4008318 ],
       [ 0.2270133 ,  0.95809883,  0.43193485,  0.83107687,  0.88557227,
         0.60693073,  0.60627751,  0.06763981,  0.15104264,  0.60024874],
       [ 0.10646665,  0.72276347,  0.21347942,  0.37033781,  0.49204702,
         0.04550423,  0.99786813,  0.42123745,  0.44224544,  0.09490401],
       [ 0.76560959,  0.91289832,  0.31627526,  0.87333601,  0.1205961 ,
         0.87200039,  0.27540055,  0.93053843

In [19]:
M_gaussian = np.random.randn(10, 10)
M_gaussian

array([[ -7.86677328e-01,   1.69290264e+00,   6.92120886e-01,
          9.03857618e-01,  -1.92661608e+00,   9.37473065e-01,
          7.45359164e-01,   1.08734712e-01,   5.58021883e-01,
          1.56140091e+00],
       [ -4.45305124e-01,   9.90271421e-01,   8.78626403e-01,
          2.11785349e+00,   2.29928261e+00,  -1.83693577e-01,
          3.44479499e-01,  -2.07053959e-01,   4.39934263e-01,
          9.40373164e-01],
       [  1.47556076e+00,   3.28649008e-01,   5.27312257e-01,
         -1.06666364e+00,  -1.30795638e+00,   3.05491024e-03,
         -5.20394882e-01,  -5.50202822e-01,   1.17721587e+00,
          9.58936398e-01],
       [  1.59747398e+00,   9.66635169e-01,  -9.42582129e-01,
          4.40174908e-01,  -2.04378276e+00,   1.52497895e+00,
         -1.08944637e+00,  -1.10176983e+00,   2.71568813e-01,
         -2.80274229e-01],
       [  5.97785481e-01,   5.69790771e-01,   1.13879024e+00,
         -2.85951810e-01,  -9.65144064e-01,  -6.13628792e-02,
          3.58252011e-01

In [23]:
M_gaussian.mean(), M_gaussian.var()

(0.17746029833030494, 0.85639879064769597)

In [24]:
A = np.random.random((3,3))
A

array([[ 0.1935942 ,  0.26458592,  0.24051549],
       [ 0.02820603,  0.73299678,  0.51089824],
       [ 0.34196658,  0.31596616,  0.04260131]])

In [25]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 3.47735388, -1.72861037,  1.09824091],
       [-4.63403088,  1.9764012 ,  2.46040145],
       [ 6.45656443, -0.78281439, -3.59062378]])

In [26]:
A_inv.dot(A)

array([[  1.00000000e+00,  -2.34733782e-16,  -1.06791189e-16],
       [  1.56768580e-16,   1.00000000e+00,  -2.29365460e-17],
       [ -1.07173602e-16,  -1.32140588e-16,   1.00000000e+00]])

In [28]:
np.linalg.det(A), np.linalg.det(A_inv)

(-0.03744224299166473, -26.707801672635284)

In [29]:
np.diag(A)

array([ 0.1935942 ,  0.73299678,  0.04260131])

In [30]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])